const AttorneyData = [
  {
    id: 1,
    name: "Sarah Johnson",
    email: "sarah.johnson@ipfirm.com",
    phone: "+1 (555) 123-4567",
    firm_name: "Johnson & Associates IP Law",
    experience_years: 12,
    specialization: "Patent Prosecution",
    assigned_cases: 5,
  },
  {
    id: 2,
    name: "Michael Chen",
    email: "michael.chen@techpatents.com",
    phone: "+1 (555) 234-5678",
    firm_name: "TechPatents LLP",
    experience_years: 8,
    specialization: "Software Patents",
    assigned_cases: 3,
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    email: "emily.rodriguez@biotechlaw.com",
    phone: "+1 (555) 345-6789",
    firm_name: "BioTech Legal Solutions",
    experience_years: 15,
    specialization: "Biotechnology Patents",
    assigned_cases: 7,
  },
  {
    id: 4,
    name: "David Kim",
    email: "david.kim@mechpatents.com",
    phone: "+1 (555) 456-7890",
    firm_name: "Mechanical Innovations Legal",
    experience_years: 10,
    specialization: "Mechanical Engineering Patents",
    assigned_cases: 4,
  },
  {
    id: 5,
    name: "Lisa Thompson",
    email: "lisa.thompson@chemip.com",
    phone: "+1 (555) 567-8901",
    firm_name: "Chemical IP Partners",
    experience_years: 14,
    specialization: "Chemical Process Patents",
    assigned_cases: 6,
  },
  {
    id: 6,
    name: "James Wilson",
    email: "james.wilson@medip.com",
    phone: "+1 (555) 678-9012",
    firm_name: "Medical Device IP Group",
    experience_years: 9,
    specialization: "Medical Device Patents",
    assigned_cases: 2,
  },
];

export default AttorneyData;
