const AttorneyData = [
  {
    id: 1,
    name: "Sarah Johnson",
    email: "sarah.johnson@ipfirm.com",
    phone: "+1 (555) 123-4567",
    firm_name: "Johnson & Associates IP Law",
    experience_years: 12,
    specialization: "Patent Prosecution",
    assigned_cases: 5,
    assigned_applications: [
      { id: "APP001", title: "AI-Based Image Recognition System" },
      { id: "APP002", title: "Smart Energy Management Platform" },
      { id: "APP003", title: "Blockchain Security Protocol" },
      { id: "APP004", title: "IoT Device Communication Method" },
      { id: "APP005", title: "Machine Learning Algorithm for Data Analysis" },
    ],
  },
  {
    id: 2,
    name: "Michael Chen",
    email: "michael.chen@techpatents.com",
    phone: "+1 (555) 234-5678",
    firm_name: "TechPatents LLP",
    experience_years: 8,
    specialization: "Software Patents",
    assigned_cases: 3,
    assigned_applications: [
      { id: "APP006", title: "Cloud Computing Resource Allocation System" },
      { id: "APP007", title: "Mobile Payment Security Framework" },
      { id: "APP008", title: "Automated Code Generation Method" },
    ],
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    email: "emily.rodriguez@biotechlaw.com",
    phone: "+1 (555) 345-6789",
    firm_name: "BioTech Legal Solutions",
    experience_years: 15,
    specialization: "Biotechnology Patents",
    assigned_cases: 7,
    assigned_applications: [
      { id: "APP009", title: "Gene Editing Technology" },
      { id: "APP010", title: "Biomedical Imaging System" },
      { id: "APP011", title: "Drug Delivery Method" },
      { id: "APP012", title: "Protein Synthesis Process" },
      { id: "APP013", title: "Medical Diagnostic Tool" },
      { id: "APP014", title: "Vaccine Development Platform" },
      { id: "APP015", title: "Cell Culture Technology" },
    ],
  },
  {
    id: 4,
    name: "David Kim",
    email: "david.kim@mechpatents.com",
    phone: "+1 (555) 456-7890",
    firm_name: "Mechanical Innovations Legal",
    experience_years: 10,
    specialization: "Mechanical Engineering Patents",
    assigned_cases: 4,
    assigned_applications: [
      { id: "APP016", title: "Advanced Manufacturing Process" },
      { id: "APP017", title: "Robotic Assembly System" },
      { id: "APP018", title: "Smart Material Design" },
      { id: "APP019", title: "Energy Efficient Engine" },
    ],
  },
  {
    id: 5,
    name: "Lisa Thompson",
    email: "lisa.thompson@chemip.com",
    phone: "+1 (555) 567-8901",
    firm_name: "Chemical IP Partners",
    experience_years: 14,
    specialization: "Chemical Process Patents",
    assigned_cases: 6,
    assigned_applications: [
      { id: "APP020", title: "Green Chemical Synthesis" },
      { id: "APP021", title: "Polymer Manufacturing Method" },
      { id: "APP022", title: "Catalyst Development Process" },
      { id: "APP023", title: "Waste Treatment Technology" },
      { id: "APP024", title: "Sustainable Material Production" },
      { id: "APP025", title: "Chemical Recycling System" },
    ],
  },
  {
    id: 6,
    name: "James Wilson",
    email: "james.wilson@medip.com",
    phone: "+1 (555) 678-9012",
    firm_name: "Medical Device IP Group",
    experience_years: 9,
    specialization: "Medical Device Patents",
    assigned_cases: 2,
    assigned_applications: [
      { id: "APP026", title: "Smart Medical Device" },
      { id: "APP027", title: "Patient Monitoring System" },
    ],
  },
];

export default AttorneyData;
